### ISSUE TITLE
Eyes of Ender not craftable

### ISSUE THREAD

**Issue by drjawa** [Civcraft/Humbug#6]
This is an old issue, but leaving this here so it is documented somewhere.

Currently only craftable by explosives factory. Fixing this shouldn't be a balance issue since Explosive Factory is cheaper (in blaze powder) than crafting vanilla.

Crafting Costs:

|Crafting Medium   |Cost (Per Eye of Ender)|
|-----------------------|------------------------------|
|Vanilla                   |1 Pearl, 1 Blaze Powder|
|Explosives Factory|1 Pearl, 0.5 Blaze Power|

**Comment by spaceFountain** [comment]
Given this is old did we ever figure out what was causing it. I assume it's related to the changes we made to limit the rate of teleportation and to make the behavior of ender pearls more predictable?

**Comment by ttk2** [comment]
not yet. Still not sure whats causing it, in theory we could just pull
plugins off of Civtest until its possible again

**Comment by rourke750** [comment]
Oh its humbug.  I thought everyone knew that?

**Comment by Xavter** [comment]
If I have time this weekend I can get to fixing this.

**Comment by jjj5311** [comment]
IIRC this is due to the custom pearl entity we use... eyes of ender are made through factories so is this necessary?

**Comment by Xavter** [comment]
It doesn't seem urgent but this forces you to use build a factory instead of simply encouraging capital investment. It's disables those who can't afford/access the capital investment from even accessing the item, thus making it more like a later stage tech like bastions instead of a vanilla item - I guess it depends on if you want eyes of ender to be a tech or a vanilla item, but unless more vanilla items are made techs, it seems out of place to have it around.

**Comment by Xavter** [comment]
I heard this was fixed, can we confirm this and close it if it's true?

**Comment by drjawa** [comment]
Adding a civtest label. Can someone try to craft eyes of ender (in crafting table)?

**Comment by jjj5311** [comment]
status?

**Comment by rourke750** [comment]
They are craftable because we commented out the the double gravity code.

**Comment by ttk2** [comment]
so then I assume this can be closed?

**Comment by suirad** [comment]
Follow-up, should this be closed?
